name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v4
        with:
          name: Doom_CooldownPulse-X.Y.Z
          path:
            - Doom_CooldownPulse.lua
            - Doom_CooldownPulse.toc
          retention-days: 1
          overwrite: true
